### ISSUE TITLE
Docker image not working on ARM64

### ISSUE THREAD

**Issue by corco** [BretFisher/bret.run#1]
While following your Udemy class, I couldn't use bretfisher/clock because the image is amd64 only and I use a Raspberry Pi as my kubernetes server (arm64).

A quick look shows that this issue affects most, if not all, of the docker images you provide throughout the course. Since multi-arch docker image are common nowaday, it would be nice if you could push a multi-arch image!

I managed to get it working with this docker buildx command (pushing to my dockerhub):

```
docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push -f clock.Dockerfile --tag corco/clock:latest .
```

As an extra motivation, the new arm Macs will likely hit the same wall!

**Comment by BretFisher** [comment]
Thanks for the issue @corco and you're right, my courses and demos need an arm64 overhaul!  In the last year I've acquired a Pi 4, and a Mac M1, so expect those images to start working this year as I update the courses.

One trick I need to work out is that most of my images use Docker Hub's autobuilds... but they don't easily support arm64 on Hub yet.

**Comment by BretFisher** [comment]
OK most in this repo are now arm v6/7/8 ready! Docker pull on arm should work, thanks to a fresh github action.

**Comment by BretFisher** [comment]
I'll close assuming this is fixed, reopen if you still have issues.
